
#define pi 3.1416
#define INDICE_OPC_MUESTREAR 1
#define INDICE_OPC_SALIR 0
#define INDICE_SEN 1
#define INDICE_LOG 2
#define INDICE_LOGLIN 3
#define INDICE_EXP 4
#define INDICE_ESC 5
#define INDICE_MRUA 6
#define INDICE_PARAB 7
#define INDICE_VOLVER 0

#define MIN_PREC 0
#define MIN_CANTIDAD_MUESTRAS 0
#define MAX_CANT_INTENTOS 3
